name: CD - Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      image_uri: 
        description: arn:aws:ecr:ap-south-1:145065858967:repository/strapi-kartik
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: |
        terraform plan -no-color \
          -var="docker_image_uri=${{ github.event.inputs.image_uri }}" \
          -var="aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -var="aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -var="aws_region=${{ secrets.AWS_REGION }}"
    - name: Terraform Apply
      run: |
        terraform apply -auto-approve \
          -var="docker_image_uri=${{ github.event.inputs.image_uri }}" \
          -var="aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -var="aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -var="aws_region=${{ secrets.AWS_REGION }}"
